### ISSUE TITLE
Fix whitelistAI comp messing with the UI

### ISSUE THREAD

**Issue by bruhmogus** [The-Arcadis-Team/arc-station-14#37]
## Description
They don't open their respective UIs

**Reproduction**
Go to a commsputer
Try to evac
"fuck off"

**Screenshots**
N/A

**Additional context**
sucks, related to the new event related computer?

**Comment by a-person5660** [comment]
door hacking ui doesnt seem to work either

**Comment by bruhmogus** [comment]
its worth noting these dont appear for aghosts, only actual characters

**Comment by Guloveos** [comment]
I have no idea whats wrong

**Comment by a-person5660** [comment]
have you tried running the yaml linter

**Comment by Guloveos** [comment]
Dunno what that is
How do I run it?

**Comment by a-person5660** [comment]
its the thing that tells you if theres anything wrong with any yaml that might cause issues exactly like this one. to run it its Content.YAMLLinter

**Comment by a-person5660** [comment]
its important to run it cause the server wont crash (usually) with a yaml error but it will still break those things so if you dont run it then these issues can fly under the radar. its also part of why you PR changes instead of commit them directly to main.

**Comment by Guloveos** [comment]
Found the problem, Its the whitelistAI comp making so you cant open the UI, Ill try and fix that soon but for now there is a fix

**Comment by TheDoctor1977** [comment]
this seems to be reoccurring in hacking UIs, consistently, but not for aghosts
