### ISSUE TITLE
FBI clothing mega-issue

### ISSUE THREAD

**Issue by bruhmogus** [The-Arcadis-Team/arc-station-14#72]
- [ ] FBI coat needs a redescription (lore breaks)
- [ ] FBI cap needs a redescription (spelling)
- [ ] FBI cap needs a flipped version to fall in line with other caps

**Comment by TheDoctor1977** [comment]
the relevant PR has since been reverted because gul forced merged it before the review was even done
these issues will be kept in mind if creator ever remakes it
