### ISSUE TITLE
Unmerge frezon sell prices

### ISSUE THREAD

**Issue by bruhmogus** [The-Arcadis-Team/arc-station-14#78]
It literally made tens of thousands of frezon mols USELESS, barely worth more than the canister buy price.

https://github.com/space-wizards/space-station-14/pull/32407

**Comment by Erisfiregamer1** [comment]
Unmerge queued for when my sanity is back from the Great AI Incident.

**Comment by Wyatt90** [comment]
Yeah AI is pretty dogshit at the moment. Might have to blow it all to smithereens and pray that reverting AI doesn't fuck something else up with how it's going at the moment

**Comment by bruhmogus** [comment]
> Yeah AI is pretty dogshit at the moment. Might have to revert AI and pray that reverting it doesn't fuck something else up with how it's going at the moment

we fixed it wyatt

**Comment by bruhmogus** [comment]
closing, ee unfucked it
