### ISSUE TITLE
Make CE able to wear hardhats

### ISSUE THREAD

**Issue by Wyatt90** [The-Arcadis-Team/arc-station-14#93]
# Description

For some UNGODLY REASON the CE can't wear ANY hardhats. They're locked to Atmospherics Technician and Station Engineer. Thanks EE/§, very cool.

**Comment by TheDoctor1977** [comment]
check again to verify this is still an issue after the recent loadout changes

**Comment by Wyatt90** [comment]
going to check again, will try closing the feature request if it's fixed

**Comment by Wyatt90** [comment]
this FR is pointless, recent loadout changes fixed it. gonna try and close now
