### ISSUE TITLE
PLEASE REMOVE EVERY SINGLE WIRE SHOCKING YOU PLEASE I BEG

### ISSUE THREAD

**Issue by Wyatt90** [The-Arcadis-Team/arc-station-14#96]
# Description

This is really fucking annoying for obvious reasons.

**Comment by bruhmogus** [comment]
is this talking about hacking?

**Comment by Wyatt90** [comment]
> is this talking about hacking?

yup

**Comment by bruhmogus** [comment]
then i 100% support this
